project_id = "yfvfklgjzmmobwfhdrqp"

[functions.seo-audit]
verify_jwt = true

[functions.competitor-analysis]
verify_jwt = true

[functions.web-scraper]
verify_jwt = true

[functions.deep-seo-analysis]
verify_jwt = true

[functions.pagespeed-analysis]
verify_jwt = true

[functions.auto-monitoring]
verify_jwt = true