project_id = "yfvfklgjzmmobwfhdrqp"

[functions.google-oauth]
verify_jwt = false

[functions.sync-search-console]
verify_jwt = true

[functions.sync-analytics]
verify_jwt = true

[functions.seo-audit]
verify_jwt = true

[functions.competitor-analysis]
verify_jwt = true

[functions.web-scraper]
verify_jwt = true

[functions.deep-seo-analysis]
verify_jwt = true

[functions.pagespeed-analysis]
verify_jwt = true

[functions.auto-monitoring]
verify_jwt = true

[functions.check-rankings]
verify_jwt = true

[functions.discover-keywords]
verify_jwt = true