// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfvfklgjzmmobwfhdrqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmdmZrbGdqem1tb2J3ZmhkcnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDk2NDIsImV4cCI6MjA3MTc4NTY0Mn0.vD7U-SosUcUr3EvaG0SPUWcORCPy2EkhIBkM-Y1uX00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});